package com.hnuc.dao;


import com.hnuc.MiniVedio.pojo.UserFan;

public interface UserFanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int insert(UserFan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int insertSelective(UserFan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    UserFan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int updateByPrimaryKeySelective(UserFan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_fans
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int updateByPrimaryKey(UserFan record);
}