package com.hnuc.pojo;

public class SearchRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_records.id
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_records.content
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_records.search_time
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    private Long searchTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_records.id
     *
     * @return the value of search_records.id
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_records.id
     *
     * @param id the value for search_records.id
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_records.content
     *
     * @return the value of search_records.content
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_records.content
     *
     * @param content the value for search_records.content
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_records.search_time
     *
     * @return the value of search_records.search_time
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    public Long getSearchTime() {
        return searchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_records.search_time
     *
     * @param searchTime the value for search_records.search_time
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    public void setSearchTime(Long searchTime) {
        this.searchTime = searchTime;
    }
}