package com.hnuc.dao;

import com.hnuc.pojo.Comment;
import com.hnuc.pojo.VO.CommentVO;

import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    Comment selectByPrimaryKey(String id);


    List<CommentVO> selectAllComment(String videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKey(Comment record);
}