package com.hnuc.dao;


import com.hnuc.pojo.VO.VideoVO;
import com.hnuc.pojo.Video;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    Video selectByPrimaryKey(String id);

    List<VideoVO> selectAllVideo(@Param("videoDesc") String videoDesc, @Param("userId") String userId);

    List<VideoVO> selectLikeVideo(String userId);

    List<VideoVO> selectFollowerVideo(String userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videos
     *
     * @mbg.generated Wed Dec 19 16:38:07 CST 2018
     */
    int updateByPrimaryKey(Video record);

    List<String> selectVideoDesc(@Param("videoDesc") String videoDesc, @Param("count") int count);
}