spring:
    #配置数据
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/minivedio?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
        username: root
        password: imhui1995
        #druid数据库连接池
        druid:
            intialSize: 1
            maxActive: 20
    thymeleaf:
      cache: false
    #配置redis
    redis:
      database: 0
      host: 192.168.74.128
      timeout: 10000
      port: 6379
      password: imhui1995
      lettuce:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: 1


mybatis:
    typeAliases: com.hnuc.pojo
    mapperLocations: classpath:mapper/*.xml

