package com.hnuc.mapper;

import com.hnuc.pojo.BGM;

public interface BGMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int insert(BGM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int insertSelective(BGM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    BGM selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKeySelective(BGM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bgm
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKey(BGM record);
}