package com.hnuc.mapper;

import com.hnuc.pojo.UserReport;

public interface UserReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int insert(UserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int insertSelective(UserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    UserReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKeySelective(UserReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_report
     *
     * @mbg.generated Tue Jan 29 14:40:24 CST 2019
     */
    int updateByPrimaryKey(UserReport record);
}